server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: gateway-service
#自定义路由规则
zuul:
  routes:
    adjustment-service: /gateway/adjustment/**
    case-service: /gateway/case/**
    employee-service: /gateway/employee/**
    finance-service: /gateway/finance/**
    fixed-loss-service: /gateway/fixed-loss/**
    schedule-service: /gateway/schedule/**
    order-service: /gateway/order/**
    document-service: /gateway/document/**
  ignored-patterns: /*-service/**
  sensitive-headers: